---
# tasks file for install_eksctl

- name: Download eksctl version
  get_url:
    url: https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz
    dest: /tmp
  tags:
    - eksctl

- name: Untar the binary to somewhere
  unarchive:
    src: /tmp/eksctl_Linux_amd64.tar.gz
    dest: /usr/local/bin
  tags:
    - eksctl

- name: Check eksctl install
  shell: eksctl version
  register: result
  tags:
    - eksctl

- debug:
    var: result
    verbosity: 2
  tags:
    - eksctl