---
# tasks file for install_kubectl

# Download the version of kubectl you want
# the kubectl_version variable is taken from this roles /vars directory

- name: Find out if this is a raspberry pi or not
  shell: uname -r
  register: raspi_status
  tags:
    - kubectl

# AMD64 non-pi install
- name: AMD64 kubectl Install
  block:
    - name: Download kubectl version
      get_url:
        url: https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl

    - name: Download the checksum for the kubectl version
      get_url:
        url: https://dl.k8s.io/{{ kubectl_version }}/bin/linux/amd64/kubectl.sha256
        dest: /usr/local/bin/kubectl.sha256
 
    - name: Validate the binary against the checksum
      command:
        cmd: echo "$(</usr/local/bin/kubectl.sha256) /usr/local/bin/kubectl" | sha256sum --check
      register: result
  when: ('raspi' not in raspi_status.stdout)
  tags:
    - kubectl
    - amd64

# ARM64 Raspberry-pi install
- name: ARM64 kubectl install
  block:
    - name: Download kubectl version
      get_url:
        url: https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/arm64/kubectl
        dest: /usr/local/bin/kubectl

    - name: Download the checksum for the kubectl version
      get_url:
        url: https://dl.k8s.io/{{ kubectl_version }}/bin/linux/arm64/kubectl.sha256
        dest: /usr/local/bin/kubectl.sha256
 
    - name: Validate the binary against the checksum
      command:
        cmd: echo "$(</usr/local/bin/kubectl.sha256) /usr/local/bin/kubectl" | sha256sum --check
      register: result
  when: ('raspi' in raspi_status.stdout)
  tags:
    - kubectl
    - arm64

- name: 
  debug:
    var: result
  tags:
    - kubectl

- name: Remove kubectl if the checksum did not match
  file:
    path: /usr/local/bin/kubectl
    state: absent
  when: '"checksum did NOT match" in result.stdout'
  tags:
    - kubectl

- name: If it passed checksum, then change the permissions on kubectl
  file:
    path: /usr/local/bin/kubectl
    user: root
    group: root
    mode: 0755
  failed_when: '"checksum did NOT match" in result.stdout'
  tags:
    - kubectl
  







 
