---
# tasks file for install_software
# Install required software for ubuntu

- name: Update first
  apt:
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  tags:
    - package_installs

- name: Install development software for Ubuntu
  apt:
    pkg:
    - ansible
    - awscli
    - curl
    - git
    - net-tools
    - pip
    - python2
    - python3
    - rpm
    - sshpass
    - wget
    - whois
    state: latest
  when: ansible_facts['distribution'] == "Ubuntu"
  tags:
    - package_installs

# Redhat
- name: Install development software for RedHat
  yum:
    name:
    - ansible
    - awscli
    - curl
    - git
    - net-tools
    - pip
    - python2
    - python3
    - rpm
    - software-properties-common
    - sshpass
    - wget
    - whois
    state: latest
  when: ansible_facts['distribution'] == "Redhat"
  tags:
    - package_installs

