---
# tasks file for install_software
# Install required software for ubuntu
- name: Install development software for Ubuntu
  apt:
    pkg:
    - ansible
    - awscli
    - curl
    - git
    - net-utils
    - pip
    - pip3
    - python2
    - python3
    - rpm
    - sshpass
    - wget
  update_cache: yes
  when: ansible_facts'[distribution'] == "Ubuntu"

# Redhat
- name: Install development software for RedHat
  yum:
    name:
    - ansible
    - awscli
    - curl
    - git
    - net-utils
    - pip
    - pip3
    - python2
    - python3
    - rpm
    - sshpass
    - wget
  state: latest
  when: ansible_facts'[distribution'] == "Redhat"


